# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
              front/src/client/.*|
              back/app/email-templates/build/.*
          )$
      - id: trailing-whitespace
        exclude: ^front/src/client/.*
  - repo: local
    hooks:
      - id: local-biome-check
        name: biome check
        entry: bash -c 'cd front && npm run lint'
        language: system
        types: [text]
        files: ^front/

      - id: local-ruff-check
        name: ruff check
        entry: uv run ruff check --force-exclude --fix --exit-non-zero-on-fix
        require_serial: true
        language: unsupported
        types: [python]

      - id: local-ruff-format
        name: ruff format
        entry: uv run ruff format --force-exclude
        require_serial: true
        language: unsupported
        types: [python]
