services:
  db:
    restart: "no"
    ports:
      - "5433:5432"

  back:
    restart: "no"
    ports:
      - "8000:8000"
    build:
      context: ./back
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
    develop:
      watch:
        - path: ./back
          action: sync
          target: /app
          ignore:
            - ./back/.venv
            - .venv
        - path: ./back/pyproject.toml
          action: rebuild
    # TODO: remove once coverage is done locally
    volumes:
      - ./back/htmlcov:/app/htmlcov
    environment:
      SMTP_HOST: "mailcatcher"
      SMTP_PORT: "1025"
      SMTP_TLS: "false"
      EMAILS_FROM_EMAIL: "noreply@example.com"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

  front:
    restart: "no"
    ports:
      - "5173:80"
    build:
      context: ./front
      args:
        - VITE_API_URL=http://localhost:8000
        - NODE_ENV=development

  playwright:
    build:
      context: ./front
      dockerfile: Dockerfile.playwright
      args:
        - VITE_API_URL=http://back:8000
        - NODE_ENV=production
    ipc: host
    depends_on:
      - back
      - mailcatcher
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://back:8000
      - MAILCATCHER_HOST=http://mailcatcher:1080
      # For the reports when run locally
      - PLAYWRIGHT_HTML_HOST=0.0.0.0
      - CI=${CI}
    volumes:
      - ./front/blob-report:/app/blob-report
      - ./front/test-results:/app/test-results
    ports:
      - 9323:9323
